# Nome do workflow que aparece no GitHub
name: CI/CD Pipeline

# Quando executar: a cada push ou pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Lista de trabalhos (jobs) a executar
jobs:
  # Job 1: CI - Testes e validação
  ci:
    # Sistema operacional para executar
    runs-on: ubuntu-latest

    # Lista de passos (steps) do job
    steps:
    # Passo 1: Baixar o código do repositório
    - name: Fazer checkout do código
      uses: actions/checkout@v4

    # Passo 2: Configurar Java 21
    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Passo 3: Executar testes
    - name: Executar testes
      run: mvn -B test --file pom.xml